name: Deploy VitePress site to Pages

on:
  # 监听 main 分支的推送
  push:
    branches: [main]
  workflow_dispatch:

  # 2. 💥 核心：配置定时巡检策略 (Cron Job) 
  # 每 30 分钟自动跑一次流水线（国际标准时间，根据需要调整）
  schedule:
    - cron: '*/30 * * * *'
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

# 这一步是关键：给 GitHub Actions 写入 Pages 的权限
permissions:
  contents: read
  pages: write
  id-token: write

  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install requests

      # 💥 核心关键：必须把 Python 爬虫放在前端打包之前！先打出 JSON 基础包
      - name: Run World Cup Scraper
        run: python get_world_cup.py

      - name: Install Node.js dependencies
        run: npm install

      # 此时 JSON 文件已经在目录里了，VitePress 编译绝对一次性顺滑通过
      - name: Build with VitePress
        run: npm run build
        env:
          VITE_DEEPSEEK_API_KEY: ${{ secrets.VITE_DEEPSEEK_API_KEY }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .vitepress/dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4